controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

index:
  path: /
  controller: App\Controller\DefaultController::index



api_user_profile:
  path: /api/user/profile
  controller: App\Controller\UserController::profile
  methods: [GET]

api_register:
  path: /api/register
  controller: App\Controller\UserController::register
  methods: [POST]

api_confirm_email:
  path: /api/confirm-email
  controller: App\Controller\UserController::confirmEmail
  methods: [POST]

api_confirm_registration:
  path: /api/confirm-registration
  controller: App\Controller\UserController::confirmRegistration
  methods: [POST]

api_users_list:
  path: /api/users
  controller: 'App\Controller\UserController::getUsers'
  methods: [GET]

api_user_get:
  path: /api/users/{id}
  controller: App\Controller\UserController::getUserById
  methods: [GET]

api_user_get_by_email:
  path: /api/users/email/{email}
  controller: App\Controller\UserController::getUserByEmail
  methods: [GET]

api_user_delete:
  path: /api/users/{id}
  controller: 'App\Controller\UserController::deleteUser'
  methods: [DELETE]

api_user_delete_by_email:
  path: /api/users/email/{email}
  controller: App\Controller\UserController::deleteUserByEmail
  methods: [DELETE]

# Routes pour PaymentController
api_create_payment_intent:
  path: /api/create-payment-intent
  controller: App\Controller\PaymentController::createPaymentIntent
  methods: [POST]

api_confirm_payment:
  path: /api/confirm-payment
  controller: App\Controller\PaymentController::confirmPayment
  methods: [POST]
# Routes pour StockageController
