services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_jmkcloud_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jmkcloud
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - jmkcloud_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_jmkcloud_container
    environment:
      PMA_HOST: mariadb_jmkcloud_container
      PMA_USER: user
      PMA_PASSWORD: userpassword
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb 

  mailer:
    image: axllent/mailpit
    container_name: mailpit_jmkcloud_container
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  jmkcloud_data: